package db.model;

import java.util.Date;

public class MachineStatus {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_status.status_id
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private Integer statusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_status.status_name
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private String statusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_status.up_date
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private Date upDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_status.del_flg
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private Integer delFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_status.status_id
	 * @return  the value of machine_status.status_id
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public Integer getStatusId() {
		return statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_status.status_id
	 * @param statusId  the value for machine_status.status_id
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_status.status_name
	 * @return  the value of machine_status.status_name
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public String getStatusName() {
		return statusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_status.status_name
	 * @param statusName  the value for machine_status.status_name
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_status.up_date
	 * @return  the value of machine_status.up_date
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public Date getUpDate() {
		return upDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_status.up_date
	 * @param upDate  the value for machine_status.up_date
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_status.del_flg
	 * @return  the value of machine_status.del_flg
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public Integer getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_status.del_flg
	 * @param delFlg  the value for machine_status.del_flg
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setDelFlg(Integer delFlg) {
		this.delFlg = delFlg;
	}
}