package db.model;

import java.util.Date;

public class MachineUse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_use.name
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_use.user_id
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_use.start_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_use.end_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_use.up_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_use.del_flg
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private Integer delFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_use.name
     *
     * @return the value of machine_use.name
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_use.name
     *
     * @param name the value for machine_use.name
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_use.user_id
     *
     * @return the value of machine_use.user_id
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_use.user_id
     *
     * @param userId the value for machine_use.user_id
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_use.start_date
     *
     * @return the value of machine_use.start_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_use.start_date
     *
     * @param startDate the value for machine_use.start_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_use.end_date
     *
     * @return the value of machine_use.end_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_use.end_date
     *
     * @param endDate the value for machine_use.end_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_use.up_date
     *
     * @return the value of machine_use.up_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_use.up_date
     *
     * @param upDate the value for machine_use.up_date
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_use.del_flg
     *
     * @return the value of machine_use.del_flg
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public Integer getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_use.del_flg
     *
     * @param delFlg the value for machine_use.del_flg
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }
}