package db.model;

import java.util.Date;

public class MachineState {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_state.state_id
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private Integer stateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_state.state_name
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private String stateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_state.up_date
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private Date upDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_state.del_flg
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	private Integer delFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_state.state_id
	 * @return  the value of machine_state.state_id
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public Integer getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_state.state_id
	 * @param stateId  the value for machine_state.state_id
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_state.state_name
	 * @return  the value of machine_state.state_name
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public String getStateName() {
		return stateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_state.state_name
	 * @param stateName  the value for machine_state.state_name
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_state.up_date
	 * @return  the value of machine_state.up_date
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public Date getUpDate() {
		return upDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_state.up_date
	 * @param upDate  the value for machine_state.up_date
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_state.del_flg
	 * @return  the value of machine_state.del_flg
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public Integer getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_state.del_flg
	 * @param delFlg  the value for machine_state.del_flg
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	public void setDelFlg(Integer delFlg) {
		this.delFlg = delFlg;
	}
}