package db.model;

import org.hibernate.validator.constraints.NotBlank;

public class Machine {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine.name
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	@NotBlank
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine.serial_no
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	private String serialNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine.user_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine.status_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	private Integer statusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine.state_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	private Integer stateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine.del_flg
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	private Integer delFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine.name
	 * @return  the value of machine.name
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine.name
	 * @param name  the value for machine.name
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine.serial_no
	 * @return  the value of machine.serial_no
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public String getSerialNo() {
		return serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine.serial_no
	 * @param serialNo  the value for machine.serial_no
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine.user_id
	 * @return  the value of machine.user_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine.user_id
	 * @param userId  the value for machine.user_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine.status_id
	 * @return  the value of machine.status_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public Integer getStatusId() {
		return statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine.status_id
	 * @param statusId  the value for machine.status_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine.state_id
	 * @return  the value of machine.state_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public Integer getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine.state_id
	 * @param stateId  the value for machine.state_id
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine.del_flg
	 * @return  the value of machine.del_flg
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public Integer getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine.del_flg
	 * @param delFlg  the value for machine.del_flg
	 * @mbggenerated  Thu Jan 18 16:48:59 JST 2018
	 */
	public void setDelFlg(Integer delFlg) {
		this.delFlg = delFlg;
	}
}