package db.model;

public class Unit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.unit_id
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private Integer unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.unit_name
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.del_flg
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    private Integer delFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.unit_id
     *
     * @return the value of unit.unit_id
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.unit_id
     *
     * @param unitId the value for unit.unit_id
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.unit_name
     *
     * @return the value of unit.unit_name
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.unit_name
     *
     * @param unitName the value for unit.unit_name
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.del_flg
     *
     * @return the value of unit.del_flg
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public Integer getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.del_flg
     *
     * @param delFlg the value for unit.del_flg
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }
}