package db.mapper;

import db.model.MachineUse;

public interface MachineUseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_use
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_use
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    int insert(MachineUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_use
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    int insertSelective(MachineUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_use
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    MachineUse selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_use
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    int updateByPrimaryKeySelective(MachineUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_use
     *
     * @mbggenerated Fri Apr 27 09:06:28 JST 2018
     */
    int updateByPrimaryKey(MachineUse record);
}