package db.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import db.model.MachineState;

@Repository
public interface MachineStateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_state
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	int deleteByPrimaryKey(Integer stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_state
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	int insert(MachineState record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_state
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	int insertSelective(MachineState record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_state
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	MachineState selectByPrimaryKey(Integer stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_state
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	int updateByPrimaryKeySelective(MachineState record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_state
	 * @mbggenerated  Fri Apr 27 09:06:28 JST 2018
	 */
	int updateByPrimaryKey(MachineState record);

	List<MachineState> selectAll();
}